//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSPPS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GMSPPSEntities : DbContext
    {
        public GMSPPSEntities()
            : base("name=GMSPPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GPMS_CLIENT> GPMS_CLIENT { get; set; }
        public virtual DbSet<GPMS_CLIENT_SUSCRIPT> GPMS_CLIENT_SUSCRIPT { get; set; }
        public virtual DbSet<GPMS_DEVICE_TYPE> GPMS_DEVICE_TYPE { get; set; }
        public virtual DbSet<GPMS_PROVIDER> GPMS_PROVIDER { get; set; }
        public virtual DbSet<GPMS_PROVIDER_CLIENTS> GPMS_PROVIDER_CLIENTS { get; set; }
        public virtual DbSet<GPMS_PROVIDER_SUPPLY> GPMS_PROVIDER_SUPPLY { get; set; }
        public virtual DbSet<GPMS_PROVIDER_SUSCRIPT> GPMS_PROVIDER_SUSCRIPT { get; set; }
        public virtual DbSet<GPMS_PROVIDER_TYP> GPMS_PROVIDER_TYP { get; set; }
        public virtual DbSet<GPMS_CLIENT_STATE> GPMS_CLIENT_STATE { get; set; }
        public virtual DbSet<GPMS_STATE> GPMS_STATE { get; set; }
        public virtual DbSet<GPMS_MISSION> GPMS_MISSION { get; set; }
        public virtual DbSet<GPMS_MISSION_ACC> GPMS_MISSION_ACC { get; set; }
        public virtual DbSet<GPMS_MISSION_CLIENT_ACC> GPMS_MISSION_CLIENT_ACC { get; set; }
        public virtual DbSet<GPMS_MISSION_STATE> GPMS_MISSION_STATE { get; set; }
    }
}
