//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSPPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPMS_MISSION_ACC
    {
        public GPMS_MISSION_ACC()
        {
            this.GPMS_MISSION_CLIENT_ACC = new HashSet<GPMS_MISSION_CLIENT_ACC>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<GPMS_MISSION_CLIENT_ACC> GPMS_MISSION_CLIENT_ACC { get; set; }
    }
}
