//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSPPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPMS_CLIENT_STATE
    {
        public int ID { get; set; }
        public int GPMS_CLIENT_ID { get; set; }
        public int GPMS_STATE_ID { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LON { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public System.Data.Entity.Spatial.DbGeography POS { get; set; }
    
        public virtual GPMS_CLIENT GPMS_CLIENT { get; set; }
        public virtual GPMS_CLIENT GPMS_CLIENT1 { get; set; }
        public virtual GPMS_STATE GPMS_STATE { get; set; }
    }
}
