//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSPPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPMS_STATE
    {
        public GPMS_STATE()
        {
            this.GPMS_CLIENT_STATE = new HashSet<GPMS_CLIENT_STATE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<GPMS_CLIENT_STATE> GPMS_CLIENT_STATE { get; set; }
    }
}
