//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSPPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPMS_MISSION_CLIENT_ACC
    {
        public int ID { get; set; }
        public Nullable<int> GPMS_MISSION_ID { get; set; }
        public Nullable<int> GPMS_CLIENT_ID { get; set; }
        public Nullable<int> GPMS_MISSION_ACC_ID { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
    
        public virtual GPMS_CLIENT GPMS_CLIENT { get; set; }
        public virtual GPMS_MISSION GPMS_MISSION { get; set; }
        public virtual GPMS_MISSION_ACC GPMS_MISSION_ACC { get; set; }
    }
}
