//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSPPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPMS_PROVIDER_SUPPLY
    {
        public GPMS_PROVIDER_SUPPLY()
        {
            this.GPMS_CLIENT_SUSCRIPT = new HashSet<GPMS_CLIENT_SUSCRIPT>();
            this.GPMS_MISSION = new HashSet<GPMS_MISSION>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GPMS_PROVIDER_ID { get; set; }
        public string SUPPLY { get; set; }
    
        public virtual ICollection<GPMS_CLIENT_SUSCRIPT> GPMS_CLIENT_SUSCRIPT { get; set; }
        public virtual GPMS_PROVIDER GPMS_PROVIDER { get; set; }
        public virtual ICollection<GPMS_MISSION> GPMS_MISSION { get; set; }
    }
}
