//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSPPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPMS_MISSION
    {
        public GPMS_MISSION()
        {
            this.GPMS_MISSION_CLIENT_ACC = new HashSet<GPMS_MISSION_CLIENT_ACC>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GPMS_PROVIDER_ID { get; set; }
        public Nullable<int> GPMS_MISSION_STATE_ID { get; set; }
        public Nullable<int> GPMS_SUPPLY_ID { get; set; }
        public string CostumMissionID { get; set; }
        public string Title { get; set; }
        public string CostumURL { get; set; }
        public string Text { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LON { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> OverTime { get; set; }
    
        public virtual GPMS_PROVIDER GPMS_PROVIDER { get; set; }
        public virtual GPMS_MISSION_STATE GPMS_MISSION_STATE { get; set; }
        public virtual GPMS_PROVIDER_SUPPLY GPMS_PROVIDER_SUPPLY { get; set; }
        public virtual ICollection<GPMS_MISSION_CLIENT_ACC> GPMS_MISSION_CLIENT_ACC { get; set; }
    }
}
