//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSPPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPMS_MISSION_STATE
    {
        public GPMS_MISSION_STATE()
        {
            this.GPMS_MISSION = new HashSet<GPMS_MISSION>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<GPMS_MISSION> GPMS_MISSION { get; set; }
    }
}
