//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSPPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPMS_PROVIDER_TYP
    {
        public GPMS_PROVIDER_TYP()
        {
            this.GPMS_PROVIDER = new HashSet<GPMS_PROVIDER>();
        }
    
        public int ID { get; set; }
        public string TYP { get; set; }
    
        public virtual ICollection<GPMS_PROVIDER> GPMS_PROVIDER { get; set; }
    }
}
